### ISSUE TITLE
README usage example doesn't work with Julia 1.11

### ISSUE THREAD

**Issue by zengmao** [JuliaPOMDP/DeepQLearning.jl#73]
Using Julia 1.11 in a fresh virtual environment, I ran the following commands:
```
]add DeepQLearning, POMDPs, Flux, POMDPModels, POMDPTools

using DeepQLearning
using POMDPs
using Flux
using POMDPModels
using POMDPTools

mdp = SimpleGridWorld();

model = Chain(Dense(2, 32), Dense(32, length(actions(mdp))))

exploration = EpsGreedyPolicy(mdp, LinearDecaySchedule(start=1.0, stop=0.01, steps=10000/2))

solver = DeepQLearningSolver(qnetwork = model, max_steps=10000, 
                             exploration_policy = exploration,
                             learning_rate=0.005,log_freq=500,
                             recurrence=false,double_q=true, dueling=true, prioritized_replay=true)

policy = solve(solver, mdp)
```

I skipped `Using POMDPSimulators` which is actually not needed in this example (and in fact would cause a precompilation error, at least with Julia 1.11). The above commands ended with the error:
```
ERROR: UndefVarError: `loadparams!` not defined in `Flux`
```

Another minor problem was that the printing of `exploration` resulted in `StackOverflowError`. This is easily avoided by appending a semicolon to the affected line to suppress the printing.

I'm using Julia Version 1.11.2 on Linux x86_64 (libc).

**Comment by zengmao** [comment]
I think it's because Flux v0.13 removed `loadparams!`, according to NEWS.md:
https://github.com/FluxML/Flux.jl/blob/cb9bb307b30b9111617e5b28ea1c5398ef3693f3/NEWS.md#v013-april-2022
To fix this, it would be necessary to modify `solver.jl`:
https://github.com/JuliaPOMDP/DeepQLearning.jl/blob/master/src/solver.jl

**Comment by zengmao** [comment]
I've submitted a pull request #74 to fix this issue.

**Comment by mykelk** [comment]
Thanks so much!

**Comment by dylan-asmar** [comment]
Should be fixed with #76. If there are still any problems, please re-open.
